# Generated by Django 4.2.13 on 2025-05-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flutterwave_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='flutterwave_tx_ref',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
