# Generated by Django 4.2.13 on 2025-05-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_flutterwave_ref_order_flutterwave_tx_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flutterwave_ref',
            field=models.CharField(blank=True, help_text='Flutterwave unique transaction ID (from verification)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='flutterwave_tx_ref',
            field=models.CharField(blank=True, help_text='Flutterwave transaction reference (used for initiation)', max_length=100, null=True, unique=True),
        ),
    ]
